/**
 * Turning an accepted proposal into graph mutations.
 *
 * The model proposed in labels; the graph works in ids. Resolving between them
 * happens HERE, at apply time, against the graph as it is now — not at
 * proposal time. Between the model answering and the author clicking Add, the
 * author may have typed, and an id captured earlier could name a concept that
 * no longer exists.
 *
 * Order is load-bearing: concepts, then the relationships that reference them,
 * then retypes, then grouping. Each step registers what it created so the next
 * can resolve against it.
 *
 * One failure never abandons the batch. Six accepted changes where the fourth
 * fails should apply five and say which one did not, because the alternative
 * is an author who accepted six and got nothing with no explanation.
 */

import { normalizeLabel } from '../../../shared/labels';
import type { ConnectionScope, MapCompletion } from '../../../shared/types/completion';
import type { KnowledgeGraph, NodeKind, RelationKind } from '../../../shared/types/graph';
import { cellMarkdownFor } from '../shared/conceptCell';
import { edgeChangeKey, edgeKey, groupingKey, nodeKey } from './proposals';

/**
 * The graph operations an apply needs. Injected so the whole path is testable
 * without a native core behind it.
 */
export interface ApplyDeps {
  addNode(label: string, kind: NodeKind): Promise<string>;
  /**
   * Write a new cell. This is what puts an accepted concept in the Editor.
   *
   * The id is generated by the caller, not here, so this module stays free of
   * anything non-deterministic.
   */
  createCell(markdown: string): Promise<void>;
  /**
   * Undo an `addNode` whose cell could not be written. Only ever called on a
   * node THIS apply created — see the rollback below.
   */
  removeNode(nodeId: string): Promise<void>;
  setNodeGroup(nodeId: string, groupId: string): Promise<void>;
  addEdge(sourceId: string, targetId: string, relation: RelationKind): Promise<string>;
  setEdgeNote(edgeId: string, note: string): Promise<void>;
  replaceEdge(
    edgeId: string,
    sourceId: string,
    targetId: string,
    relation: RelationKind,
  ): Promise<string>;
}

export interface ApplyFailure {
  readonly subject: string;
  readonly reason: string;
}

export interface ApplyReport {
  readonly applied: number;
  readonly failures: readonly ApplyFailure[];
}

function messageOf(error: unknown): string {
  if (error instanceof Error && error.message) return error.message;
  if (typeof error === 'string' && error.length > 0) return error;
  return 'the graph refused the change';
}

/**
 * Apply the selected changes, in dependency order.
 *
 * `selected` is the set of proposal keys the author left checked. Anything not
 * in it is skipped silently — that is not a failure, it is a decision.
 */
export async function applyCompletion(
  completion: MapCompletion,
  selected: ReadonlySet<string>,
  graph: KnowledgeGraph,
  deps: ApplyDeps,
  scope: ConnectionScope = 'all',
): Promise<ApplyReport> {
  const idByLabel = new Map<string, string>();
  for (const node of graph.nodes) {
    const key = node.normalizedLabel || normalizeLabel(node.label);
    if (!idByLabel.has(key)) idByLabel.set(key, node.id);
  }

  const groupIds = new Set(
    graph.nodes.filter((node) => node.kind === 'group').map((node) => node.id),
  );

  // Existing relationships, keyed the way a proposal names them.
  const edgeIdByPair = new Map<string, string>();
  const labelOf = new Map(
    graph.nodes.map((node) => [node.id, node.normalizedLabel || normalizeLabel(node.label)]),
  );
  for (const edge of graph.edges) {
    const source = labelOf.get(edge.source);
    const target = labelOf.get(edge.target);
    if (source && target) edgeIdByPair.set(`${source}|${target}`, edge.id);
  }

  const idFor = (label: string): string | undefined => idByLabel.get(normalizeLabel(label));

  const facetsByLabel = new Map<string, Array<{ label: string; parent: string }>>();
  for (const parent of graph.nodes) {
    for (const subnode of parent.subConcepts ?? []) {
      const key = normalizeLabel(subnode.label);
      const owners = facetsByLabel.get(key) ?? [];
      owners.push({ label: subnode.label, parent: parent.label });
      facetsByLabel.set(key, owners);
    }
  }

  /**
   * Core edges need persisted ids, but a persisted endpoint is still a nested
   * subnode when an authored parent owns it. Materialise only the addressable
   * endpoint; never create an Editor cell or turn it into a top-level concept.
   */
  const facetFor = (label: string, parent?: string): { label: string; parent: string } | undefined => {
    const facets = facetsByLabel.get(normalizeLabel(label)) ?? [];
    if (!parent) return facets.length === 1 ? facets[0] : undefined;
    const parentKey = normalizeLabel(parent);
    return facets.find((candidate) => normalizeLabel(candidate.parent) === parentKey);
  };

  const ensureEndpointId = async (label: string, parent?: string): Promise<string | undefined> => {
    const facet = facetFor(label, parent);
    if (parent && !facet) return undefined;
    const existing = idFor(facet?.label ?? label);
    if (existing) return existing;
    if (!facet) return undefined;

    const nodeId = await deps.addNode(facet.label, 'concept');
    idByLabel.set(normalizeLabel(facet.label), nodeId);
    return nodeId;
  };

  type EndpointLevel = 'group' | 'node' | 'subnode';
  const endpointLevel = (label: string, parent?: string): EndpointLevel | null => {
    if (parent) return facetFor(label, parent) ? 'subnode' : null;
    const existingId = idFor(label);
    if (existingId) {
      const existing = graph.nodes.find((node) => node.id === existingId);
      if (existing?.kind === 'group') return 'group';
      if (existing && existing.cellIds.length === 0 && facetFor(label)) return 'subnode';
      return 'node';
    }
    return facetFor(label) ? 'subnode' : null;
  };
  const pairScope = (source: EndpointLevel, target: EndpointLevel): Exclude<ConnectionScope, 'all'> => {
    if (source === target) return `${source}-${target}` as Exclude<ConnectionScope, 'all'>;
    const levels = new Set([source, target]);
    if (levels.has('group')) return levels.has('subnode') ? 'group-subnode' : 'group-node';
    return 'node-subnode';
  };

  const failures: ApplyFailure[] = [];
  let applied = 0;

  // -- concepts -------------------------------------------------------------

  for (const node of completion.newNodes) {
    if (!selected.has(nodeKey(node.label))) continue;
    // Older main-process validators emitted a synthetic newNode for every
    // nested endpoint. Treat that stale artifact as a no-op, never as a real
    // concept creation; the edge loop materializes the child without a cell.
    if (facetsByLabel.has(normalizeLabel(node.label))) continue;
    if (scope !== 'all') {
      failures.push({
        subject: node.label,
        reason: `a ${scope} scan may only connect existing endpoints`,
      });
      continue;
    }

    const normalized = normalizeLabel(node.label);
    // addNode dedups by normalized label, so an accepted concept the author
    // already had comes back as the EXISTING id. Rolling that one back below
    // would delete work this proposal never created.
    const existedBefore = idByLabel.has(normalized);

    let nodeId: string;
    try {
      nodeId = await deps.addNode(node.label, node.kind);
    } catch (error: unknown) {
      failures.push({ subject: node.label, reason: messageOf(error) });
      continue;
    }

    idByLabel.set(normalized, nodeId);
    applied += 1;

    /*
     * The concept now exists, but it is not REACHABLE until its cell does.
     *
     * Editing and deleting a concept both go through the cell whose
     * [[wikilink]] asserts it. A node with no cell is absent from the Editor
     * and has no delete in NodeDetail, so it is stranded in the graph for
     * good — reported as "I can't edit or delete the financing and capex
     * nodes". That is not a partial success, so a failed cell write takes the
     * node back out and reports the concept as not applied.
     */
    try {
      await deps.createCell(cellMarkdownFor(node.label, node.note));
    } catch (cellError: unknown) {
      applied -= 1;

      if (existedBefore) {
        // Nothing to undo: the node is the author's, from before this apply.
        failures.push({
          subject: node.label,
          reason: `it was already in the graph and its cell could not be written: ${messageOf(cellError)}`,
        });
        continue;
      }

      try {
        await deps.removeNode(nodeId);
        idByLabel.delete(normalized);
        failures.push({
          subject: node.label,
          reason: `its cell could not be written, so the concept was not added: ${messageOf(cellError)}`,
        });
      } catch (rollbackError: unknown) {
        // Best effort. Nothing further to try, so say plainly that the node is
        // sitting on the canvas rather than let the author discover it.
        failures.push({
          subject: node.label,
          reason:
            `its cell could not be written (${messageOf(cellError)}) and the concept is ` +
            `still in the graph: ${messageOf(rollbackError)}`,
        });
      }
      continue;
    }

    if (node.group) {
      const groupId = idFor(node.group);
      if (groupId && groupIds.has(groupId)) {
        try {
          await deps.setNodeGroup(nodeId, groupId);
        } catch (error: unknown) {
          failures.push({
            subject: `${node.label} — placing it in "${node.group}"`,
            reason: messageOf(error),
          });
        }
      }
    }
  }

  // -- relationships --------------------------------------------------------

  for (const edge of completion.newEdges) {
    if (!selected.has(edgeKey(
      edge.source,
      edge.target,
      edge.sourceParent,
      edge.targetParent,
    ))) continue;
    const subject = `${edge.source} → ${edge.target}`;
    const sourceLevel = endpointLevel(edge.source, edge.sourceParent);
    const targetLevel = endpointLevel(edge.target, edge.targetParent);
    if (
      scope !== 'all' &&
      (!sourceLevel || !targetLevel || pairScope(sourceLevel, targetLevel) !== scope)
    ) {
      failures.push({ subject, reason: `this is not a ${scope} relationship` });
      continue;
    }

    let sourceId: string | undefined;
    let targetId: string | undefined;
    try {
      sourceId = await ensureEndpointId(edge.source, edge.sourceParent);
      targetId = await ensureEndpointId(edge.target, edge.targetParent);
    } catch (error: unknown) {
      failures.push({ subject, reason: messageOf(error) });
      continue;
    }
    if (!sourceId || !targetId) {
      // Reachable when the author unchecked a concept this edge needed, or
      // deleted one between the proposal and the apply.
      failures.push({
        subject,
        reason: `"${sourceId ? edge.target : edge.source}" is not in the graph`,
      });
      continue;
    }

    try {
      const edgeId = await deps.addEdge(sourceId, targetId, edge.relation);
      if (edge.note) await deps.setEdgeNote(edgeId, edge.note);
      applied += 1;
    } catch (error: unknown) {
      failures.push({ subject, reason: messageOf(error) });
    }
  }

  // -- retyped relationships ------------------------------------------------

  for (const change of completion.edgeChanges) {
    if (!selected.has(edgeChangeKey(
      change.source,
      change.target,
      change.sourceParent,
      change.targetParent,
    ))) continue;
    const subject = `${change.source} → ${change.target}`;
    const sourceLevel = endpointLevel(change.source, change.sourceParent);
    const targetLevel = endpointLevel(change.target, change.targetParent);
    if (
      scope !== 'all' &&
      (!sourceLevel || !targetLevel || pairScope(sourceLevel, targetLevel) !== scope)
    ) {
      failures.push({ subject, reason: `this is not a ${scope} relationship` });
      continue;
    }

    const sourceId = idFor(change.source);
    const targetId = idFor(change.target);
    const edgeId = edgeIdByPair.get(
      `${normalizeLabel(change.source)}|${normalizeLabel(change.target)}`,
    );
    if (!sourceId || !targetId || !edgeId) {
      failures.push({ subject, reason: 'that relationship is no longer in the graph' });
      continue;
    }

    try {
      // Replacing mints a new id, so the note has to go on the new edge.
      const replacedId = await deps.replaceEdge(edgeId, sourceId, targetId, change.relation);
      if (change.note) await deps.setEdgeNote(replacedId, change.note);
      applied += 1;
    } catch (error: unknown) {
      failures.push({ subject, reason: messageOf(error) });
    }
  }

  // -- grouping -------------------------------------------------------------

  for (const grouping of completion.groupAdditions) {
    if (!selected.has(groupingKey(grouping.node, grouping.group))) continue;
    const subject = `${grouping.node} → ${grouping.group}`;
    if (scope !== 'all') {
      failures.push({ subject, reason: `group membership is outside a ${scope} scan` });
      continue;
    }

    const nodeId = idFor(grouping.node);
    const groupId = idFor(grouping.group);
    if (!nodeId || !groupId || !groupIds.has(groupId)) {
      failures.push({ subject, reason: 'the concept or the group is no longer in the graph' });
      continue;
    }

    try {
      await deps.setNodeGroup(nodeId, groupId);
      applied += 1;
    } catch (error: unknown) {
      failures.push({ subject, reason: messageOf(error) });
    }
  }

  return { applied, failures };
}
